language: node_js
node_js:
  - "6.1"
deploy:
  provider: lambda
  function_name: "crawler"
  region: "ap-northeast-1"
  role: "arn:aws:iam::514115015388:role/lambda_basic_execution"
  runtime: "nodejs6.10"
  handler_name: "handler.crawler"
  access_key_id: "AWS ID"
  secret_access_key: "AWS SECRET KEY"
